Repository yeon2lee/lionproject_movie-review, pull requests merged in 2021-07, with the labels that each got.

#4 add CRUD
  movie_review/urls.py
  review/admin.py
  review/forms.py
  review/models.py
  review/templates/detail.html
  review/templates/edit.html
  review/templates/home.html
  review/templates/new.html
  review/urls.py
  review/views.py
Labels: CRUD

#6 add search
  review/templates/home.html
  review/templates/search.html
  review/urls.py
  review/views.py
Labels: search

#10 add comment
  review/admin.py
  review/forms.py
  review/models.py
  review/templates/detail.html
  review/urls.py
  review/views.py
Labels: comment
